repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: no-commit-to-branch
        args: [--branch, master]
      - id: check-merge-conflict
        types: [python]
      - id: check-ast
        types: [python]
      - id: debug-statements
        types: [python]
        exclude: src/deepomatic/workflows/v2/client/*
      - id: trailing-whitespace
        types: [python]
      - id: detect-private-key
      - id: check-json
      - id: check-yaml
      - id: check-toml

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.2.1
    hooks:
      - id: autoflake
        files: '^src/deepomatic/workflows/'

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.1
    hooks:
      - id: mypy
        args: ["--ignore-missing-imports"]
        files: '^src/deepomatic/workflows/'

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        files: '^src/deepomatic/workflows/'

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        files: '^src/deepomatic/workflows/'
        args: ["--profile", "black", "--filter-files"]
